# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-26 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pomiar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('wynik', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Sonda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('położenie', models.CharField(max_length=100)),
                ('ostatni_pomiar', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='pomiar',
            name='sonda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pomiary.Sonda'),
        ),
    ]
