# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 12:59
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomiary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pomiar',
            options={'verbose_name_plural': 'Pomiary'},
        ),
        migrations.AlterModelOptions(
            name='sonda',
            options={'verbose_name_plural': 'Sondy'},
        ),
        migrations.AddField(
            model_name='sonda',
            name='kolor',
            field=colorful.fields.RGBColorField(default='#D3D3D3'),
        ),
    ]
