# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 19:05
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pomiary', '0002_auto_20170331_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dzien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('wynik', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Dni',
            },
        ),
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('wynik', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Fragmenty',
            },
        ),
        migrations.CreateModel(
            name='Miesiac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('wynik', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Miesiące',
            },
        ),
        migrations.AddField(
            model_name='sonda',
            name='data_ostatni_dzien',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sonda',
            name='data_ostatni_fragment',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sonda',
            name='data_ostatni_miesiac',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sonda',
            name='kolor',
            field=colorful.fields.RGBColorField(default='#000000'),
        ),
        migrations.AddField(
            model_name='miesiac',
            name='sonda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pomiary.Sonda'),
        ),
        migrations.AddField(
            model_name='fragment',
            name='sonda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pomiary.Sonda'),
        ),
        migrations.AddField(
            model_name='dzien',
            name='sonda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pomiary.Sonda'),
        ),
    ]
