# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pomiary', '0003_auto_20170601_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Przerwa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_przerwy', models.CharField(max_length=100)),
                ('czas_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('czas_koniec', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Przerwy',
            },
        ),
    ]
