# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pomiary', '0004_przerwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przerwa',
            name='czas_koniec',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='przerwa',
            name='czas_start',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='przerwa',
            name='nazwa_przerwy',
            field=models.CharField(default='Brak nazwy', max_length=100),
        ),
    ]
