# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomiary', '0005_auto_20170602_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sonda',
            old_name='ostatni_pomiar',
            new_name='ostatni_pomiar_data',
        ),
        migrations.AddField(
            model_name='sonda',
            name='ostatni_pomiar_wynik',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
